### ISSUE TITLE
Improve speed of reading VCF files

### ISSUE THREAD

**Issue by apriha** [apriha/snps#11]
The current implementation can take a long time to read VCFs. Consider using [CyVCF](https://github.com/arq5x/cyvcf), or [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) to read VCFs. The `pandas` implementation would likely be similar to the existing `snps.io._write_vcf`.

**Comment by willgdjones** [comment]
I ended up taking a look at this in #32
