### ISSUE TITLE
openSNPs downloads

### ISSUE THREAD

**Issue by afaulconbridge** [apriha/snps#117]
It seems that openSNP has changed their downloads, a single zip file is no longer available. This breaks some of the analysis code, which is where I found this problem as I want to investigate and compare some alternative sex detection mechanisms.  I'll take a look and see if I can work out a solution in a pull request.

**Comment by apriha** [comment]
Thanks for the issue @afaulconbridge , see here: https://github.com/arvkevi/ezancestry/pull/7#issuecomment-704094720

Hi @gedankenstuecke, could you start the process to regenerate the data dump file? Thanks again!

**Comment by gedankenstuecke** [comment]
Hey @afaulconbridge @apriha, sorry for the problem with the download. I've kicked our server to regenerate it! Give it a few hours to process the data and then it should work :-)

**Comment by apriha** [comment]
Thanks @gedankenstuecke , that worked!
