### ISSUE TITLE
Consider using dask

### ISSUE THREAD

**Issue by apriha** [apriha/snps#12]
[dask](https://dask.org) would help with reading large VCFs and could potentially increase the speed of calculations throughout (e.g., remapping and writing VCFs).

**Comment by castedo** [comment]
I'm not that familiar with the VCF format but it doesn't sound like parsing it should have a bottleneck in computation (in contrast to IO) If the bottleneck is computational rather than IO then it sounds like the solution is determine the slow code to speed up rather than parallelize with dask (and if the bottleneck is IO then parallelizing doesn't help).

**Comment by apriha** [comment]
VCFs can be over 30M rows and 3GB uncompressed, and [dask.dataframe](https://docs.dask.org/en/latest/dataframe.html#dataframe) could help with larger datasets like those.

I agree that code could be optimized throughout, but I think there is also benefit to parallelization when processing chromosome-by-chromosome (e.g., via [dask.delayed](https://docs.dask.org/en/latest/delayed.html)).

**Comment by castedo** [comment]
Chromosome-by-chromosome is a great idea for calculations and processing potentially getting sped up ... AFTER the VCF file has been read. But the reading stage of the VCF file is still going to be serial and not parallelizable. Or perhaps I don't realize that the VCF format is more complex and allows random file position access or something.
I'm guessing that I'd like to use snps without dask in which case it'd be nice if dask was a soft dependency and VCFs could be read into either dask or pandas dataframes. But this is hypothetical and just a thought/suggestion.
Regardless, that would be pretty cool and impressive to compute on GBs of SNP data chromosome-by-chromosome in parallel! :)

**Comment by apriha** [comment]
Thanks, @castedo. I think if dask was used, having it as an optional dependency could be possible.

In the example above, dask would be used for two separate purposes: 1) handle large VCFs / datasets in memory 2) perform computations in parallel (not necessarily reading a VCF).

**Comment by apriha** [comment]
PR #33 adds the capability to efficiently read large VCFs; therefore, this is less of an issue so closing for now.
