### ISSUE TITLE
Getting "404: Not Found" when trying to use get_opensnp_datadump_filenames()

### ISSUE THREAD

**Issue by mkbond777** [apriha/snps#130]
I am getting 404 error when trying to access filenames using 

```
from snps.resources import Resources
r = Resources()
files = r.get_opensnp_datadump_filenames()
```

Code Link:
https://github.com/apriha/snps/blob/d69dc0fed4bb14b6dfde7de1372c717bdfbdf3ca/src/snps/resources.py#L265

**Comment by apriha** [comment]
Thanks for the issue. Sometimes the openSNP data dump returns 404... see [here](https://github.com/openSNP/snpr/issues/534).

As a temporary fix, the @openSNP team can can kickoff a process to recreate the archive. Can you help @gedankenstuecke? 🙂 Thanks again.

**Comment by gedankenstuecke** [comment]
Yep, I kicked our server to generate a new file. Sorry for that!
