### ISSUE TITLE
Read/Write to memory buffer

### ISSUE THREAD

**Issue by willgdjones** [apriha/snps#16]
Currently, the `Reader` and `Writer` classes within `io` read and write files from the filesystem. E.g.

https://github.com/apriha/snps/blob/7e5d622aa800def88bb9dc0df0cf6cf3e8d5e7b2/src/snps/io.py#L71-L73

I have a use case where it would be useful to be able to read and write from [buffered IO](https://docs.python.org/3/library/io.html).

I'm happy to implement this in the coming days and submit a PR, but I wanted to ask what your opinions on this would be.

Thanks!

Will

**Comment by apriha** [comment]
Thanks, @willgdjones. @gedankenstuecke, @arvkevi, and @castedo have also been discussing this over at [Open Humans](https://www.openhumans.org) as well, so I definitely agree that this is a feature worth adding.

I think around the code you point out is a good place to handle this use case... Feel free to run with it and submit a PR. Thanks again!
