### ISSUE TITLE
documentation for reading VCF missing

### ISSUE THREAD

**Issue by DSLituiev** [apriha/snps#18]
The readme says that there the package is able to read VCF, but there is no example how to read  them (only write). Trying to read VCFv4.1 

```
fn_struct = 'my.vcf'
sc = SNPs(fn_struct)
sc.build
# 0
```

returns 0 records, though pyVCF works OK:

```
vcf_reader = vcf.Reader(filename =fn_struct)
sum((1 for record in vcf_reader))
# 184353
```

**Comment by apriha** [comment]
Thanks for the issue. Passing the path to the VCF file is correct; however, `snps` currently does not read VCF records if there is no RSID.

So, I agree that the documentation should be updated to show an example of how to read a VCF. Also, additional notes could be added to the [`read_vcf`](https://github.com/apriha/snps/blob/344220e0a49c0c54032e46aead75e9c838da214d/src/snps/io.py#L433) docstring to discuss the assumptions made when reading VCF files (currently captured in comments throughout the function).
