### ISSUE TITLE
Questions: regarding using VCF & PLINK input files

### ISSUE THREAD

**Issue by PhilPalmer** [apriha/snps#34]
Hi,

Thanks for a great tool. 

Is there support (or plans to support) the following:
1. [Annotation](https://www.biostars.org/p/227652/) of missing rsids in a VCF file? (Similiar to how liftover is currently performed. Just seen https://github.com/apriha/snps/issues/19 which seems the same)
2. Compressed VCF input files? (Eg with bgzip or gzip)
3. [PLINK binary](https://www.cog-genomics.org/plink/1.9/formats#bed) input files?

Thanks in advance,
Phil

**Comment by apriha** [comment]
Hey Phil, thanks for the questions. Hopefully these answers help:

1. Currently, missing RSIDs are not annotated and are skipped when reading a VCF. If there was a resource that could be downloaded that maps an RSID to a chromosome and position, then this could be implemented; it's being tracked in #19. (Note that #33 adds an `unannotated_vcf` property for now.)
2. `gzip` compressed VCF are also handled in #33
3. Currently there's no support for these files.

Thanks again!

**Comment by apriha** [comment]
No problems! Thanks again.
