### ISSUE TITLE
Help to set output directory

### ISSUE THREAD

**Issue by apedreira** [apriha/snps#36]
Hello

I'm trying to convert a .csv from FTDNA to .vcf 

I get load my .csv (the assembly and build are OK) and I set the ouptut dir throught:

`snps.SNPs(output_dir='C:Users\\Desktop\\')`. 

The execution return:

 `SNPs('')`

when I save the .csv throught: 

`s = SNPs('C:\\Users\\PC\\Desktop\\genome.csv')`
s.save_snps(vcf=True)

I get
`'output\\FTDNA_GRCh37.vcf'`

But not generates any file

What I'm doing wrong?

Thanks in advance

**Comment by apriha** [comment]
Hi, the output directory is set when reading in a file. Try something like this:

```
from snps import SNPs
s = SNPs("path/to/input/file.csv", output_dir="path/to/output")
s.save_snps(vcf=True)
```

Does that help?

**Comment by apedreira** [comment]
Thank you a lot @apriha 
It works perfectly

**Comment by apriha** [comment]
Great to hear! Thanks for the question @apedreira .

**Comment by arvkevi** [comment]
Thanks @apriha 😄

**Comment by apedreira** [comment]
I have a new issue  😕 Although Imputer can acces to FamilyTreeDNA integration, this only admits .csv files comprresed as .gz I got compress vcf as .gz with PeaZip but didn't works when I upload the file (Openhumans sends an automatic mail explaining the problem) So.. How I should upload the file?

Sorry for so many questions
