### ISSUE TITLE
Exception catching

### ISSUE THREAD

**Issue by willgdjones** [apriha/snps#38]
Hi @apriha,

I noticed throughout the codebase that Exceptions are caught and not raised to the user. This creates some challenges in tracking down the cause of bugs when they crop up.

I would propose either:

1. Logging the Exception message and the offending like that caused the Exception.
2. Allowing the Exception to be raised without catching it and allowing execution to continue.

It would be great to get your thoughts!

Thanks,
Will

**Comment by apriha** [comment]
Hey Will, thanks for the suggestion. I agree that exceptions should be raised to help debugging, and I think option 2 would be more Pythonic. Check out PR #39 and let me know what you think!
