### ISSUE TITLE
Remove duplication of X chromosome alleles

### ISSUE THREAD

**Issue by apriha** [apriha/snps#43]
With the X chromosome, if only one allele is reported for a SNP, the allele is doubled such that the X chromosome `genotype` will always be a string of length 2. Some data sources report two X chromosome alleles for all X chromosome SNPs, even if the individual is a male. So, by doubling single alleles, this makes all X chromosome data consistent.

However, instead of doubling alleles, it'd be better to analyze the X chromosome SNPs to determine if only one allele should be reported (i.e., if an individual is male). Any heterozygous SNPs not in the pseudoautosomal region could then be flagged as a discrepant SNP.

**Comment by castedo** [comment]
I can suggest a cut-off for whether the number of heterozygous  X chromsome SNPs indicates a female vs a male with discrepant SNPs. I've used 3.125% which seems to work OK. I can maybe write up a deeper analysis if you think that would be valuable.

**Comment by apriha** [comment]
Thanks @castedo.

**Comment by willgdjones** [comment]
I'm going to take a look at this now.

**Comment by willgdjones** [comment]
I will initially use the threshold of 3.125% that was suggested by @castedo .

**Comment by willgdjones** [comment]
When working on this, I noticed that there are sometimes duplicate rsids which means that I am not able to overwrite the `genotype` column values. We could `drop_duplicates` in the index and take the value of the `first` occurrence which would make things a lot simpler. Thoughts?

https://stackoverflow.com/questions/27236275/what-does-valueerror-cannot-reindex-from-a-duplicate-axis-mean

**Comment by apriha** [comment]
Dropping duplicate SNPs sounds good. However, I think we should track them as discrepant SNPs that get returned after loading a file (same as returning any heterozygous SNPs in the non-PAR region as discrepant SNPs for a file determined to be male).

**Comment by willgdjones** [comment]
I have made a start at this here: https://github.com/apriha/snps/pull/48

I was not 100% sure the best way to add the discrepant SNPs but we can discuss in the PR.
