### ISSUE TITLE
Detect build 38 Exome files

### ISSUE THREAD

**Issue by willgdjones** [apriha/snps#47]
I have been using the `detect_build` functionality and I have noticed that `snps` does not correct detect our build 38 Exome VCFs. This is likely because Exome data is not technically within scope of the genotype data that snps originally was intended to support.

It seems that the rsids that are listed here are not present in my Exome file. I am looking to find some more examples of rsids that are included in common Exome files so that this functionality is extended in the same way that you have originally implemented it.

https://github.com/apriha/snps/blob/master/src/snps/__init__.py#L398

Let me know your thoughts!

Will

**Comment by apriha** [comment]
I think that sounds like a great idea! Also, a generic fall-back method to detect the build of an RSID not in the lookup table would also solve this (see #6).

**Comment by apriha** [comment]
@willgdjones , would the capability added in #72 fix this issue? If not, can you identify a few additional rsids that occur in these files we could use to detect the build? Thanks again!

**Comment by willgdjones** [comment]
I think this is going to fix the issue. Looking forward to trying it out!

Sent via Superhuman iOS ( https://sprh.mn/?vip=williamgdjones@gmail.com )

**Comment by apriha** [comment]
Hi @willgdjones , I'm assuming this is no longer an issue... Thanks again!
