### ISSUE TITLE
Can't save snps object generated from VCF

### ISSUE THREAD

**Issue by PhilPalmer** [apriha/snps#53]
Hi,

I am trying to read and output a VCF file using the SNPs library. I would like to do this to check that the VCF is valid and remap if the file is not from the GRCh37 reference genome.

However, I am getting the error: `no data to save...` when I try and save the my SNPs object to a file.

### Download data:
```bash
# download small VCF data
wget https://lifebit-featured-datasets.s3-eu-west-1.amazonaws.com/modules/beagle5/test/subsampled/FR07961001.pass.recode.subsampled.vcf.gz
gzip -d FR07961001.pass.recode.subsampled.vcf.gz
```

### Run SNPs:
```python
from snps import SNPs
import logging, sys

# for logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler(sys.stdout))

input_file = 'FR07961001.pass.recode.subsampled.vcf'
snps = SNPs(input_file)
snps.save_snps()
```

### Output:
`no data to save...`

The snps object does seem to be empty:
```python
df = snps.snps
df.columns.values
# array(['chrom', 'pos', 'genotype'], dtype=object)
len(df)
# 0
```

However, I also tried reading the input VCF line by line with SNPs using the following:
```
with open(input_file, 'r') as f:
  snps = SNPs(f.read().encode('utf-8'))
```

And then when I outputted this object it seemed to have the data:
![image](https://user-images.githubusercontent.com/32334279/72277018-15788380-3629-11ea-9dd1-ed126c1d09a8.png)

But I'm not sure if there are any issues with reading the format of the VCF:
![image](https://user-images.githubusercontent.com/32334279/72278658-5faf3400-362c-11ea-85e3-c77b45b5fae2.png)

Any ideas what might be going wrong. Any help would be much appreciated.

Many thanks in advance,
Phil

**Comment by willgdjones** [comment]
Hi @PhilPalmer - I've investigated this and it seems that the VCF you have linked to is unannotated (nothing in the IDs column) so the `snps` package is unable to create retrieve any rsids from the file. You'll need to annotate this file before loading it into snps. We could potentially have some better logging so that it is clearer that this is what is going on!

**Comment by willgdjones** [comment]
In your case, to find out what rsids are available in the `snps` object, you can use `snps.snps`.

**Comment by PhilPalmer** [comment]
Okay, that's easy to fix. Thanks @willgdjones for the prompt reply!
