### ISSUE TITLE
Errors running tests on MacOSX

### ISSUE THREAD

**Issue by willgdjones** [apriha/snps#77]
I'm getting errors across the whole test suite when running them locally on my Mac OSX Catalina 10.15.4 machine.

```
    os.makedirs(path, exist_ok=True)
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py:213: in makedirs
    makedirs(head, exist_ok=exist_ok)
/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py:223: in makedirs
    mkdir(name, mode)
E   FileNotFoundError: [Errno 2] No such file or directory: '../../../../var/folders/h3/k5sgzmp17cvbz1mm459fkf200000gn/T/tmp9ixj7r4i/fasta'
```

Looking around, I think this is something to [do with the permissions on the `/var/folders/` directories](https://github.com/ocaml/opam/issues/3576)

Is there a way we can specify what temporary to use here?

**Comment by apriha** [comment]
You should be able to specify the path to the temporary directory via an environment variable. See https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp

**Comment by willgdjones** [comment]
Setting `TMPDIR` worked 👍 . Thanks!
